name: boot-kotlin-co

on:
  push:
    paths:
      - "boot-kotlin-co/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"
          cache: "maven"
      - name: Set up Database
        run: |
          docker-compose up -d postgres
          sleep 5
          docker ps -a
      - name: Build with Maven
        run: mvn -B clean test --file boot-kotlin-co/pom.xml
