name: boot-data-r2dbc

on:
  push:
    paths:
      - "boot-data-r2dbc/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"
          cache: "maven"
      - name: Build with Maven
        run: mvn -B package --file boot-data-r2dbc/pom.xml
