name: boot

on:
  push:
    paths:
      - "boot/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "maven"
      - name: Set up Database
        run: |
          docker-compose up -d postgres
          sleep 5
          docker ps -a
      - name: Build with Maven
        run: mvn -B package --file boot/pom.xml -Put

    # commits code quality analysis
  intergration-test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "maven"
      - name: Set up Database
        run: |
          docker-compose up -d postgres
          sleep 5
          docker ps -a
      - name: Build with Maven(E2e testing)
        run: mvn -B verify --file boot/pom.xml -Pit

  dockerize:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "maven"
      - name: Build with Maven(Build Docker Image)
        run: |
          mvn spring-boot:build-image  --file boot/pom.xml -DskipTests
          docker image ls
      - name: Run application in Docker Container
        run: |
          docker-compose --file ./docker-compose.yml up -d postgres
          sleep 10
          docker-compose  --file ./docker-compose.yml --file ./boot/docker-compose.local.yml up -d app
          sleep 10
          docker ps -a
          docker-compose --file ./docker-compose.yml --file ./boot/docker-compose.local.yml logs
      - name: Build with Maven(SmokeTest)
        env:
          BASE_API_URL: http://localhost:9999
        run: |
          mvn -B verify --file boot/pom.xml -Psmoke
      # Skip the Docker publishing steps.
      #- name: Login to DockerHub Registry
      #  run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      #- name: Push Docker Image
      #  run: docker push hantsy/spring6-sample-boot
