name: jdbc-client

on:
  push:
    paths:
      - "jdbc-client/**"
    branches:
      - master
  pull_request:
    paths:
      - "jdbc-client/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: "maven"

      - name: Build with Maven
        run: mvn -B -q clean package --file jdbc-client/pom.xml
        
      - name: Start up PostgreSQL in Docker
        run: |
          docker-compose up -d postgres
          sleep 5
          docker ps -a
          
      - name: Unit Tests
        run: mvn -B -q clean test --file jdbc-client/pom.xml -Put

      - name: Integration Tests
        run: mvn -B -q clean verify --file jdbc-client/pom.xml -Pit

