name: test-properties-factory

on:
  push:
    paths:
      - "test-properties-factory/**"
    branches:
      - master
  pull_request:
    paths:
      - "test-properties-factory/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: "maven"

      - name: Build with Maven
        run: mvn -B -q clean test --file test-properties-factory/pom.xml
        
