name: virtual-thread

on:
  push:
    paths:
      - "virtual-thread/**"
    branches:
      - master
  pull_request:
    paths:
      - "virtual-thread/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 21
          cache: "maven"

      - name: Build with Maven
        run: mvn -B -q clean package --file virtual-thread/pom.xml
